using Kitchenhelper.Core.Services;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System.Net.Http;
using System.Text;
using System.Text.Json;

namespace Kitchenhelper.Infrastructure.Services;

/// <summary>
/// ASR implementation using Google Gemini 1.5.
/// Uses Gemini's audio understanding capabilities for speech-to-text.
/// </summary>
public class GeminiAsrService : IAsrService
{
    private readonly ILogger<GeminiAsrService> _logger;
    private readonly HttpClient _httpClient;
    private readonly string _apiKey;
    private const string GeminiApiUrl = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent";

    public GeminiAsrService(
        ILogger<GeminiAsrService> logger,
        IHttpClientFactory httpClientFactory,
        IConfiguration configuration)
    {
        _logger = logger;
        _httpClient = httpClientFactory.CreateClient();
        _apiKey = configuration["Gemini:ApiKey"] ?? throw new InvalidOperationException("Gemini API key not configured");
    }

    public async Task<string> TranscribeAsync(string audioFilePath)
    {
        _logger.LogInformation("Transcribing audio file: {AudioPath}", audioFilePath);

        if (!File.Exists(audioFilePath))
            throw new FileNotFoundException("Audio file not found", audioFilePath);

        try
        {
            // Read audio file as base64
            var audioBytes = await File.ReadAllBytesAsync(audioFilePath);
            var audioBase64 = Convert.ToBase64String(audioBytes);

            // Prepare Gemini API request
            var requestBody = new
            {
                contents = new[]
                {
                    new
                    {
                        parts = new object[]
                        {
                            new
                            {
                                inline_data = new
                                {
                                    mime_type = "audio/wav",
                                    data = audioBase64
                                }
                            },
                            new
                            {
                                text = "Please transcribe this audio file. Provide only the transcript text without any formatting, labels, or additional commentary. If the audio contains a recipe or cooking instructions, transcribe exactly what is said."
                            }
                        }
                    }
                },
                generationConfig = new
                {
                    temperature = 0.1,
                    topK = 1,
                    topP = 1,
                    maxOutputTokens = 8192
                }
            };

            var json = JsonSerializer.Serialize(requestBody);
            var content = new StringContent(json, Encoding.UTF8, "application/json");

            var requestUrl = $"{GeminiApiUrl}?key={_apiKey}";
            var response = await _httpClient.PostAsync(requestUrl, content);

            if (!response.IsSuccessStatusCode)
            {
                var errorContent = await response.Content.ReadAsStringAsync();
                _logger.LogError("Gemini API error: {StatusCode} - {Error}", response.StatusCode, errorContent);
                throw new InvalidOperationException($"Gemini API request failed: {response.StatusCode}");
            }

            var responseJson = await response.Content.ReadAsStringAsync();
            var result = JsonDocument.Parse(responseJson);

            // Extract transcript from response
            var candidates = result.RootElement.GetProperty("candidates");
            if (candidates.GetArrayLength() == 0)
                throw new InvalidOperationException("No transcript generated by Gemini");

            var firstCandidate = candidates[0];
            var content_parts = firstCandidate.GetProperty("content").GetProperty("parts");
            
            if (content_parts.GetArrayLength() == 0)
                throw new InvalidOperationException("Empty transcript from Gemini");

            var transcript = content_parts[0].GetProperty("text").GetString();

            if (string.IsNullOrWhiteSpace(transcript))
                throw new InvalidOperationException("Empty transcript result");

            _logger.LogInformation("Transcription successful, length: {Length} characters", transcript.Length);
            return transcript.Trim();
        }
        catch (Exception ex) when (ex is not InvalidOperationException)
        {
            _logger.LogError(ex, "Failed to transcribe audio using Gemini");
            throw new InvalidOperationException("Transcription failed", ex);
        }
    }
}
